### ISSUE TITLE
JPA testing with exceptions

### ISSUE THREAD

**Issue by AnselmC** [dajudge/testee.fi#2]
Hi @dajudge 

me again.
I'm currently trying to test my jpa connection to a postgresql database.
I set up the TestData as is described in your blog post and my other test cases are working fine.
However, I am having difficulty with a test concerning a unique key constraint.
Here's the test class: 
```
	@Test
	public void tryToEnterDuplicateTest() {
		try {
			this.entityManager.persist(PersistencyTest.createBean(24L, 1L));
			// this.entityManager.flush(); // Un-commenting this will lead to the exception
			Assert.fail("A duplicate key error should have been thrown");
		} catch (final PersistenceException e) {
			Assert.assertThat(e.getMessage(), CoreMatchers.containsString("FEHLER: doppelter Schlüsselwert"));
		}
	}
```

For some reason calling persist() does not throw an error. But when TestEEfi flushes the entity manager, the exception occurs and the test fails. If I add a flush() call on the entity manager in the try clause the exception will be thrown there and the test case passed but the overall run fails. 
Here's the part of the log where the error occurs:

> 15:32:37.328 [main] DEBUG fi.testee.jdbc.TesteeDataSource - Creating connection jdbc/commentdb
> 15:32:37.576 [main] DEBUG fi.testee.services.JpaInjectionServicesImpl - Flushing EntityManagers
> [EL Warning]: 2017-09-25 15:32:37.585--UnitOfWork(1544562778)--Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.6.0.v20150309-bf26070): org.eclipse.persistence.exceptions.DatabaseException
> Internal Exception: org.postgresql.util.PSQLException: FEHLER: doppelter Schlüsselwert verletzt Unique-Constraint »p_comment«
>   Detail: Schlüssel »(id)=(1)« existiert bereits.
> Error Code: 0
> Call: INSERT INTO T_COMMENT (ID, CHANGEDATE, CREATEDATE, CREATOR, OBJECTID, TEXT, VERSION) VALUES (?, ?, ?, ?, ?, ?, ?)
> 	bind => [1, 2017-09-25 15:32:37.294, 2017-09-25 15:32:37.294, Creator, 24, Text, 1]
> Query: InsertObjectQuery(CommentBean:1)
> 15:32:37.589 [main] DEBUG fi.testee.runtime.TransactionalContext - Shutting down transactional context
> 15:32:37.590 [main] DEBUG fi.testee.jdbc.TesteeDataSource - Committing connection jdbc/commentdb on TesteeDataSource{name='jdbc/commentdb'}

Any suggestions? If you need any more info, please let me know.

Thanks!
Anselm

**Comment by dajudge** [comment]
Hallo @AnselmC,

what as far as I can see what describe is standard JPA behavior. A JPA implementation is not required to actually persist your object to the database unless you
- Execute EntityManager.flush()
- Execute a query - e.g. with EntityManager.createQuery()
- Commit the transaction

You can read more on this for example here: https://stackoverflow.com/questions/6925649/jpa-not-insert-the-data-in-the-row-after-persist

So if I understand your test correctly then the call to EntityManager.flush() is required to exhibit the desired behavior. 

Am I interpreting your situation correctly?

Best regards,
Alex

**Comment by AnselmC** [comment]
Thanks, has been resolved!
